# Generated by Django 2.2.4 on 2019-08-16 06:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banner/%Y%m', verbose_name='轮播图')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否首页显示')),
                ('test_number', models.IntegerField(default=0, verbose_name='测试人数')),
                ('push_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='推送时间')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
            },
        ),
        migrations.CreateModel(
            name='TestIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.CharField(max_length=500, verbose_name='介绍')),
                ('theory', models.CharField(max_length=500, verbose_name='理论')),
                ('notice', models.CharField(max_length=500, verbose_name='须知')),
            ],
            options={
                'verbose_name': '测试说明页',
                'verbose_name_plural': '测试说明页',
            },
        ),
        migrations.CreateModel(
            name='TestName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='测试名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='category.TestName', verbose_name='父级测试')),
            ],
            options={
                'verbose_name': '测评分类名称',
                'verbose_name_plural': '测评分类名称',
            },
        ),
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='index/%Y%m', verbose_name='轮播图')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('is_index_show', models.BooleanField(default=True, verbose_name='是否首页显示')),
                ('is_class_show', models.BooleanField(default=True, verbose_name='是否分类页显示')),
                ('test_number', models.IntegerField(default=0, verbose_name='测试人数')),
                ('test_dec', models.CharField(max_length=100, verbose_name='测试简介')),
                ('push_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='推送时间')),
                ('child_test_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_test_name', to='category.TestName', verbose_name='二级测试名称')),
                ('parent_test_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_test_name', to='category.TestName', verbose_name='一级测试名称')),
            ],
            options={
                'verbose_name': '测试详情',
                'verbose_name_plural': '测试详情',
            },
        ),
    ]
