# Generated by Django 2.2.4 on 2019-08-14 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banner/%Y%m', verbose_name='轮播图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '评估轮播图',
            },
        ),
        migrations.CreateModel(
            name='ClassBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='classbanner/%Y%m', verbose_name='轮播图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '课程分类轮播图',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='date_birth',
            field=models.DateField(auto_now_add=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='users',
            name='education',
            field=models.CharField(max_length=10, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.BooleanField(choices=[('male', '男'), ('female', '女')], default='male', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='users',
            name='grade',
            field=models.CharField(max_length=10, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=10, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.IntegerField(null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profession',
            field=models.CharField(max_length=20, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='users',
            name='real_name',
            field=models.CharField(max_length=10, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='school',
            field=models.CharField(max_length=20, null=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='users',
            name='vocation',
            field=models.CharField(max_length=20, null=True, verbose_name='意向行业'),
        ),
    ]
